INSERT INTO videos (dancetype, dancelevel, movetitle, link)
VALUES
  ('Salsa','beginner','How To Spin Your Partner','46dybRGrCsc'),
  ('Salsa','beginner','Make your basic step look more natural','9CzGaubcqQg'),
  ('Salsa','beginner', 'Closed position lead setup' ,'vWeJbJgkTFQ'),
  ('Salsa','intermediate', 'Pencil turns' ,'ADysVrHMp3g'),
  ('Salsa','intermediate', 'Lady double turn' ,'TDoyttBpzU0'),
  ('Salsa','intermediate', 'Underarm turns' ,'lhu6spVILW8'),
  ('Salsa','advanced', 'Back spot turn into cross body lead' ,'ln9nxU-xN6A'),
  ('Salsa','advanced', 'Breakaway turn (inspired by Lindy hop)' ,'ziH6X4QHITY'),
  ('Salsa','advanced', 'Back spot turn into titanic' ,'yPkNaOGyAyc'),
  ('Bachata','beginner', 'Side basic and forward basic with simple turn' ,'tgRMUVD1FeM'),
  ('Bachata','beginner', 'Beginning Bachata footwork' ,'yz8JhAA_foE'),
  ('Bachata','beginner', '6 Bachata Basic Steps' ,'TJGfUGUoZe0'),
  ('Bachata','intermediate', 'Alternating turns into slide' ,'j3Fshk1NWyA'),
  ('Bachata','intermediate', 'Syncopation steps by Alemana' ,'Znytk6hMyj4'),
  ('Bachata','intermediate', 'Side to side footwork (kick shuffles)' ,'Lco4bvPyz5A'),
  ('Bachata','advanced', 'More advanced footwork (nice rotational moves with Texas Tommy)' ,'5R8bhnseysk'),
  ('Bachata','advanced', 'Bachata advanced footwork' ,'FVi_SaJPeqA'),
  ('Bachata','advanced', 'Dips and lunges' ,'Esd3BlxUXdU'),
  ('Merengue','beginner', 'basic steps' ,'KO_hobER7SU'),
  ('Merengue','beginner', 'Side together side steps' ,'OAp3IknZmV8'),
  ('Merengue','beginner', 'Side to side, turns, basic combinations' ,'UDSbJAy6ehQ'),
  ('Merengue','intermediate', 'Rainbow separation step' ,'emmJJkf2DFo'),
  ('Merengue','intermediate', 'Colocho' ,'FJ5MrZsPIjQ'),
  ('Merengue','intermediate', 'Basket' ,'3CxuhGMF6R8'),
  ('Merengue','advanced', 'Wrap to tunnel' ,'4d1u1P36HWk'),
  ('Merengue','advanced', 'Hammerlock to behind the back' ,'70J6zISofBk'),
  ('Merengue','advanced', 'Conga breaks with crossing action' ,'SHOOMxiSD-k')
  
  